-- "Generate from existing tests" feature: a mock test can be generated by
-- feeding the AI the statistical shape (topic distribution, question-type
-- ratio, marking scheme) of one or more existing mock tests - never their
-- question text, so token cost scales with the OUTPUT question count only,
-- and the AI structurally can't reproduce the source questions since it
-- never sees them. This table is pure provenance/display data ("Generated
-- from: JEE Main 2024, JEE Main 2025" on the resulting test's page) - it
-- plays no role in generation itself, which reads its inputs from
-- processing_jobs.input_config (see mock-tests.service.js#generateFromExisting).
--
-- No uploaded_files/processing_jobs schema change needed for this feature -
-- processing_jobs.uploaded_file_id was already nullable (001_initial_schema.sql
-- never made it NOT NULL). The one real gap was worker/db.py#claim_next_job's
-- INNER JOIN against uploaded_files, which would silently never match (and
-- so never claim) a job with a NULL uploaded_file_id - fixed to a LEFT JOIN
-- alongside this migration, not a schema change.
CREATE TABLE IF NOT EXISTS mock_test_generation_sources (
  mock_test_id UUID NOT NULL REFERENCES mock_tests(id) ON DELETE CASCADE,
  source_mock_test_id UUID NOT NULL REFERENCES mock_tests(id) ON DELETE CASCADE,
  PRIMARY KEY (mock_test_id, source_mock_test_id)
);

CREATE INDEX IF NOT EXISTS idx_mock_test_generation_sources_mock_test_id
  ON mock_test_generation_sources (mock_test_id);
